Repository doorooful/CapstoneProject, pull requests merged in 2023-10, with the labels that each got.

#174 Slang module v2 upgrade
  dt-demo-be/modules/slang/run.py
  dt-demo-be/modules/slang/slang_dict_v3.xlsx
Labels: demo, backend

#176 Refactored and designed Document class
  docs/backend/issue173_Document_Sentence_class_design.png
  docs/backend/issue173_Document_Sentence_class_design.pu
  docs/backend/issue173_detection_report_information_call_flow.png
  docs/backend/issue173_detection_report_information_call_flow.pu
  dt-demo-be/app_lab.py
  dt-demo-be/document.py
Labels: documentation, implementation, backend

#167 upload file from frontend to backend
  dt-demo-be/app.py
  dt-demo-fe/src/components/file/uploadBtn.js
  dt-demo-fe/src/hooks/api/axiosInterceptor.js
  dt-demo-fe/src/pages/filtering/filelist.js
Labels: enhancement, Frontend

#179 Upgrade spc module second version
  dt-demo-be/modules/spc/run.py
  dt-demo-be/modules/spc/spc_dict_v1.xlsx
  dt-demo-be/modules/spc/spc_dict_v2.xlsx
Labels: enhancement, backend

#180 PDD module upgrade v2
  dt-demo-be/modules/pdd/run.py
Labels: bug, enhancement, demo, backend

#187 update detection report creation method
  dt-demo-be/app_lab.py
  dt-demo-be/templates/filter_report/detection_template.html
  dt-demo-fe/src/components/Rules/ruleOptions.js
  dt-demo-fe/src/components/templates/detectionReportTemplate.js
  dt-demo-fe/src/components/templates/report/generateReport.js
  dt-demo-fe/src/pages/filtering/detectionReport.js
  dt-demo-fe/src/pages/filtering/rules.js
Labels: enhancement, Frontend, backend

#194 Bugfix: to return original_highlighted_content
  dt-demo-be/document.py
Labels: bug

#196 Bug fixed on get_conv_report() api result
  dt-demo-be/document.py
Labels: bug

#197 update conversion report creation method
  dt-demo-be/document.py
  dt-demo-be/templates/filter_report/conversion_template.html
  dt-demo-fe/src/components/templates/conversionReportTemplate.js
  dt-demo-fe/src/components/templates/detectionReportTemplate.js
  dt-demo-fe/src/components/templates/report/generateReport.js
  dt-demo-fe/src/pages/filtering/conversionReport.js
  dt-demo-fe/src/pages/filtering/detectionReport.js
Labels: enhancement, Frontend

#199 sprocessing DB update
  dt-demo-be/app_lab.py
  dt-demo-be/document.py
  dt-demo-fe/src/components/file/uploadBtn.js
Labels: implementation, backend

#201 Main page design and refactoring
  dt-demo-fe/src/components/Navbar/NavbarElements.js
  dt-demo-fe/src/components/Navbar/index.js
  dt-demo-fe/src/components/file/uploadBtn.js
  dt-demo-fe/src/components/main/descriptions.js
  dt-demo-fe/src/components/main/inquiry.js
  dt-demo-fe/src/components/report/generateReport.js
  dt-demo-fe/src/components/report/htmlStringToPdf.js
  dt-demo-fe/src/pages/01_home.js
  dt-demo-fe/src/pages/filtering/rules.js
Labels: Frontend
