Repository doorooful/CapstoneProject, pull requests merged in 2023-09, with the labels that each got.

#70 navigation bar implementation
  .gitignore
  dt-demo-fe/README.md
  dt-demo-fe/package-lock.json
  dt-demo-fe/package.json
  dt-demo-fe/public/favicon.ico
  dt-demo-fe/public/index.html
  dt-demo-fe/public/logo192.png
  dt-demo-fe/public/logo512.png
  dt-demo-fe/public/manifest.json
  dt-demo-fe/public/robots.txt
  dt-demo-fe/src/App.css
  dt-demo-fe/src/App.js
  dt-demo-fe/src/App.test.js
  dt-demo-fe/src/assets/fonts/Amiko/Amiko-Bold.ttf
  dt-demo-fe/src/assets/fonts/Amiko/Amiko-Regular.ttf
  dt-demo-fe/src/assets/fonts/Amiko/Amiko-SemiBold.ttf
  dt-demo-fe/src/components/Navbar/NavbarElements.js
  dt-demo-fe/src/components/Navbar/index.js
  dt-demo-fe/src/index.css
  dt-demo-fe/src/index.js
  dt-demo-fe/src/logo.svg
  dt-demo-fe/src/pages/01_home.js
  dt-demo-fe/src/pages/02_filter.js
  dt-demo-fe/src/pages/03_converter.js
  dt-demo-fe/src/pages/04_statistics.js
  dt-demo-fe/src/reportWebVitals.js
  dt-demo-fe/src/setupTests.js
Labels: implementation, Frontend

#77 Backend server setup
  dt-demo-be/README.md
  dt-demo-be/app.py
  dt-demo-fe/README.md
  dt-demo-fe/src/pages/02_filter.js
  dt-demo-fe/src/pages/03_converter.js
  dt-demo-fe/src/pages/04_statistics.js
  dt-demo-fe/src/setupProxy.js
Labels: implementation, Frontend

#79 package information updated
  dt-demo-fe/README.md
  dt-demo-fe/package-lock.json
  dt-demo-fe/package.json
  dt-demo-fe/src/App.js
Labels: bug

#88 slang module added
  dt-demo-be/app.py
  dt-demo-be/modules/slang/run.py
Labels: implementation, backend

#90 typo module and sequential processing
  dt-demo-be/app.py
  dt-demo-be/modules/run.py
  dt-demo-be/modules/slang/run.py
  dt-demo-be/modules/typo/run.py
Labels: implementation, backend

#93 Remaining modules: Pdd, Duplication / `--all` modules running option
  dt-demo-be/app.py
  dt-demo-be/modules/dup/run.py
  dt-demo-be/modules/pdd/run.py
  dt-demo-be/modules/slang/run.py
Labels: implementation, backend

#94 Issue91 button implementation
  dt-demo-fe/README.md
  dt-demo-fe/src/Router.js
  dt-demo-fe/src/pages/02_filter.js
  dt-demo-fe/src/pages/demo/filelist.js
  dt-demo-fe/src/pages/demo/report.js
  dt-demo-fe/src/pages/demo/rules.js
  dt-demo-fe/src/pages/demo/upload.js
Labels: implementation

#98 router bug fix
  dt-demo-fe/src/Router.js
Labels: bug

#99 Filtering Rules Implementation
  dt-demo-be/app.py
  dt-demo-fe/package-lock.json
  dt-demo-fe/package.json
  dt-demo-fe/src/Router.js
  dt-demo-fe/src/components/Rules/ruleOptions.js
  dt-demo-fe/src/hooks/api/axiosInterceptor.js
  dt-demo-fe/src/pages/02_filter.js
  dt-demo-fe/src/pages/demo/rules.js
Labels: implementation, Frontend

#117 Preparing report data: details table
  .gitignore
  dt-demo-be/app.py
  dt-demo-be/templates/filter_report/template.html
Labels: implementation, backend

#119 Read contents(txt) file to create report
  dt-demo-be/app.py
  dt-demo-be/templates/filter_report/template.html
Labels: backend

#121 Get files from server
  dt-demo-fe/src/Router.js
  dt-demo-fe/src/components/file/uploadBtn.js
  dt-demo-fe/src/pages/02_filter.js
  dt-demo-fe/src/pages/demo/filelist.js
  dt-demo-fe/src/pages/demo/upload.js
  dt-demo-fe/src/pages/filtering/filelist.js
  dt-demo-fe/src/pages/filtering/report.js
  dt-demo-fe/src/pages/filtering/rules.js
Labels: implementation, Frontend, backend

#124 rules_box & get_files bug fixed
  dt-demo-fe/src/Router.js
  dt-demo-fe/src/pages/filtering/filelist.js
  dt-demo-fe/src/pages/filtering/rules.js
Labels: bug

#127 get_files API response code
  dt-demo-be/app.py
Labels: backend

#125 upload input files' info
  dt-demo-be/app.py
  dt-demo-fe/src/components/file/uploadBtn.js
  dt-demo-fe/src/pages/filtering/filelist.js
Labels: implementation, Frontend, backend

#130 Temporal bug fix: typo module
  dt-demo-be/modules/typo/run.py
Labels: bug

#134 create new folder(spc) and run.py under the spc
  dt-demo-be/modules/run.py
  dt-demo-be/modules/spc/run.py
Labels: enhancement, backend

#142 add conversion report page
  dt-demo-be/app.py
  dt-demo-fe/src/Router.js
  dt-demo-fe/src/components/file/uploadBtn.js
  dt-demo-fe/src/pages/02_filter.js
  dt-demo-fe/src/pages/filtering/detectionReport.js
  dt-demo-fe/src/pages/filtering/index.js
  dt-demo-fe/src/pages/filtering/report.js
  dt-demo-fe/src/pages/filtering/rules.js
Labels: implementation, Frontend

#143 Report template updated
  dt-demo-be/app.py
  dt-demo-be/templates/filter_report/template.html
Labels: implementation, backend

#145 Error rate calculation for report
  dt-demo-be/app.py
  dt-demo-be/templates/filter_report/template.html
Labels: implementation, backend

#147 Detection report creation
  dt-demo-be/app.py
  dt-demo-be/templates/filter_report/conversion_template.html
  dt-demo-be/templates/filter_report/detection_template.html
Labels: demo, backend

#153 update font url
  dt-demo-fe/src/styles/reset.js
Labels: bug

#151 Implement spc(special character replacing) module
  dt-demo-be/modules/spc/run.py
  dt-demo-be/modules/spc/spc_dict_v1.xlsx
Labels: implementation, backend

#155 detection report viewer
  dt-demo-be/templates/filter_report/detection_template.html
  dt-demo-fe/README.md
  dt-demo-fe/src/pages/02_filter.js
  dt-demo-fe/src/pages/filtering/detectionReport.js
Labels: implementation, Frontend

#156 conversion report viewer
  dt-demo-be/templates/filter_report/conversion_template.html
  dt-demo-fe/src/components/file/uploadBtn.js
  dt-demo-fe/src/pages/filtering/conversionReport.js
Labels: implementation, Frontend

#161 information for detection report fetching from db
  database/README.md
  dt-demo-be/app_lab.py
  dt-demo-be/det_report.py
Labels: implementation, backend

#166 Upgrade spc module and large scale test
  dt-demo-be/README.md
  dt-demo-be/modules/spc/run.py
Labels: enhancement, backend
